# Generated by Django 5.1.4 on 2025-01-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, null=True)),
                ('bill_number', models.CharField(max_length=100, null=True)),
                ('bill_date', models.DateField(auto_now=True)),
                ('quantity', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('gst_amount', models.FloatField(default=0)),
                ('bill_amount', models.FloatField(default=0)),
                ('product_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
            ],
        ),
    ]
